import json
import os
import time
from urllib import error as urlerror
from urllib import request as urlrequest


class GroqFaultAnalysisService:
    """Handles structured fault interpretation with Groq API."""

    def __init__(self):
        self.api_key = os.getenv("GROQ_API_KEY", "").strip()
        self.primary_model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        self.base_url = os.getenv("GROQ_API_URL", "https://api.groq.com/openai/v1")
        self.max_retries = int(os.getenv("GROQ_MAX_RETRIES", "3"))
        # Fallback model candidates for when primary is decommissioned
        fallback_models = os.getenv(
            "GROQ_FALLBACK_MODELS",
            "llama-3.3-70b-versatile,llama-3.2-90b-vision-preview,gemma-2-9b-it,llama-3.1-8b-instant"
        )
        self.model_candidates = self._build_model_candidates(self.primary_model, fallback_models)

    def analyze_fault(self, fault_json, architecture_context, fault_history):
        if not self.api_key:
            raise RuntimeError("Missing GROQ_API_KEY. Add it to your environment before using AI fault interpretation.")

        prompt = self._build_prompt(fault_json, architecture_context, fault_history)

        try:
            raw = self._call_with_retry(prompt, task_type="fault_analysis")
            parsed = self._parse_response(raw)
        except RuntimeError as err:
            message = str(err)
            if "HTTP 429" in message or "quota" in message.lower() or "rate" in message.lower():
                return self._local_fallback_analysis(fault_json, message)
            raise

        return {
            "root_cause_explanation": parsed.get("root_cause_explanation", "No root cause explanation returned."),
            "mitigation_plan": parsed.get("mitigation_plan", []),
            "preventive_recommendations": parsed.get("preventive_recommendations", []),
            "confidence_notes": parsed.get("confidence_notes", "Generated by Groq based on provided context.")
        }

    def analyze_cascading_effects(self, industry, machinery_type, fault_type, machinery_options=None):
        """Generate cascading effects using Groq and enforce at least one cascading impact."""
        if not self.api_key:
            raise RuntimeError(
                "Missing GROQ_API_KEY. Add it to your environment before using LLM cascading analysis."
            )

        prompt = self._build_cascading_prompt(industry, machinery_type, fault_type, machinery_options or [])
        raw = self._call_with_retry(prompt, task_type="cascading")
        parsed = self._parse_response(raw)
        normalized = self._normalize_cascading_output(parsed, industry, machinery_type, fault_type)

        # Hard requirement: always return at least one cascading effect.
        if not normalized["cascading_effects"]:
            repair_prompt = (
                "Return ONLY valid JSON. You MUST provide at least one cascading effect with explanation.\n"
                "Schema:\n"
                "{\n"
                '  "root_cause": {"industry":"string","machinery":"string","fault":"string","severity":"critical|high|medium|low","explanation":"string"},\n'
                '  "cascading_effects": [{"level":1,"affected_machinery":"string","possible_faults":["string"],"cascade_risk":"critical|high|medium|low","cascade_explanation":"string"}],\n'
                '  "systemic_impact_summary": "string"\n'
                "}\n"
                f"Context: industry={industry}, machinery={machinery_type}, fault={fault_type}."
            )
            repair_raw = self._call_with_retry(repair_prompt, task_type="cascading_repair")
            repair_parsed = self._parse_response(repair_raw)
            normalized = self._normalize_cascading_output(repair_parsed, industry, machinery_type, fault_type)

        if not normalized["cascading_effects"]:
            raise RuntimeError(
                "Groq did not return valid cascading effects. Please retry with the same selection."
            )

        normalized["total_affected_systems"] = 1 + len(normalized["cascading_effects"])
        return normalized

    def _build_prompt(self, fault_json, architecture_context, fault_history):
        fault_text = json.dumps(fault_json or {}, indent=2)
        architecture_text = json.dumps(architecture_context or {}, indent=2)
        history_text = json.dumps(fault_history or [], indent=2)

        return (
            "You are a senior reliability engineer for an intelligent fault management system.\n"
            "Analyze the provided fault data, system architecture context, and recent fault history.\n"
            "Return ONLY valid JSON with this exact schema:\n"
            "{\n"
            '  "root_cause_explanation": "string",\n'
            '  "mitigation_plan": ["step 1", "step 2"],\n'
            '  "preventive_recommendations": ["recommendation 1", "recommendation 2"],\n'
            '  "confidence_notes": "string"\n'
            "}\n"
            "Be specific, practical, and avoid generic language.\n"
            "Fault JSON:\n"
            f"{fault_text}\n\n"
            "System Architecture Context:\n"
            f"{architecture_text}\n\n"
            "Recent Fault History:\n"
            f"{history_text}"
        )

    def _build_cascading_prompt(self, industry, machinery_type, fault_type, machinery_options):
        machinery_text = json.dumps(machinery_options or [], indent=2)

        return (
            "You are a senior power-system reliability engineer.\n"
            "Given the selected industry, machinery, and fault, generate cascading impact analysis.\n"
            "You MUST always include at least one cascading effect.\n"
            "If uncertainty exists, infer the most plausible downstream impact in transmission/protection/asset chain.\n"
            "Return ONLY valid JSON with this exact schema:\n"
            "{\n"
            '  "root_cause": {\n'
            '    "industry": "string",\n'
            '    "machinery": "string",\n'
            '    "fault": "string",\n'
            '    "severity": "critical|high|medium|low",\n'
            '    "explanation": "string"\n'
            "  },\n"
            '  "cascading_effects": [\n'
            "    {\n"
            '      "level": 1,\n'
            '      "affected_machinery": "string",\n'
            '      "possible_faults": ["string", "string"],\n'
            '      "cascade_risk": "critical|high|medium|low",\n'
            '      "cascade_explanation": "string"\n'
            "    }\n"
            "  ],\n"
            '  "systemic_impact_summary": "string"\n'
            "}\n"
            "Rules:\n"
            "1) cascading_effects must have length >= 1.\n"
            "2) level must start at 1 and increase by 1.\n"
            "3) Each cascade_explanation must explain mechanism and operational consequence.\n"
            "4) Keep it realistic for power systems and substations.\n"
            "5) Do not include markdown, comments, or extra keys.\n\n"
            f"Industry: {industry}\n"
            f"Selected Machinery: {machinery_type}\n"
            f"Fault Type: {fault_type}\n"
            f"Available machinery in this industry: {machinery_text}\n"
        )

    def _call_with_retry(self, prompt_text, task_type="fault_analysis"):
        """Call Groq API with retry and model fallback logic."""
        endpoint = f"{self.base_url}/chat/completions"
        last_error = None

        # Determine temperature and max_tokens based on task
        if task_type in {"cascading", "cascading_repair"}:
            temperature = 0.3 if task_type == "cascading" else 0.2
            max_tokens = 1200 if task_type == "cascading" else 800
        else:
            temperature = 0.2
            max_tokens = 900

        # Try each model candidate
        for model_name in self.model_candidates:
            model_not_available = False

            for attempt in range(1, self.max_retries + 1):
                payload = {
                    "model": model_name,
                    "messages": [
                        {
                            "role": "user",
                            "content": prompt_text
                        }
                    ],
                    "temperature": temperature,
                    "max_tokens": max_tokens,
                }
                
                body = json.dumps(payload).encode("utf-8")

                request_obj = urlrequest.Request(
                    endpoint,
                    data=body,
                    headers={
                        "Content-Type": "application/json",
                        "Authorization": f"Bearer {self.api_key}",
                        "Accept": "application/json",
                        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
                        "Accept-Language": "en-US,en;q=0.9",
                        "Cache-Control": "no-cache",
                        "Pragma": "no-cache"
                    },
                    method="POST"
                )

                try:
                    with urlrequest.urlopen(request_obj, timeout=35) as response:
                        response_data = response.read()
                        # Handle gzip-compressed responses if needed
                        if response_data[:2] == b'\x1f\x8b':  # gzip magic number
                            import gzip
                            response_data = gzip.decompress(response_data)
                        return json.loads(response_data.decode("utf-8"))
                except urlerror.HTTPError as err:
                    details = err.read().decode("utf-8", errors="ignore")
                    lower_details = details.lower()
                    last_error = RuntimeError(f"Groq API HTTP {err.code}: {details[:400]}")

                    # Check if model is decommissioned
                    if err.code == 400 and "decommissioned" in lower_details:
                        model_not_available = True
                        break

                    # Auth/permission errors - don't retry
                    if err.code in {401, 403}:
                        break
                    
                    # Rate limit or server errors - retry
                    if err.code in {429, 500, 502, 503}:
                        if attempt < self.max_retries:
                            time.sleep(2 ** (attempt - 1))
                            continue
                    
                    # Other 400 errors - try next model
                    if err.code == 400:
                        model_not_available = True
                        break

                except Exception as err:
                    last_error = RuntimeError(f"Groq API request failed: {str(err)}")
                    if attempt < self.max_retries:
                        time.sleep(2 ** (attempt - 1))
                        continue

                break

            # If model is decommissioned or not available, try next one
            if model_not_available:
                continue

            # Other errors - don't try other models
            break

        raise last_error or RuntimeError(
            "Groq API request failed after retries and model fallback. "
            "Verify GROQ_API_KEY is valid and at least one model is available."
        )

    def _build_model_candidates(self, primary_model, fallback_models_csv):
        """Build list of model candidates, removing duplicates."""
        seen = set()
        models = []

        for model in [primary_model] + fallback_models_csv.split(","):
            normalized = str(model or "").strip()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            models.append(normalized)

        return models or ["llama-3.3-70b-versatile"]

    def _parse_response(self, raw_response):
        try:
            choices = raw_response.get("choices") or []
            if not choices:
                return {}
            
            message = choices[0].get("message", {})
            content = message.get("content", "").strip()
            
            if not content:
                return {}
            
            # Try to extract JSON from the response
            # Sometimes LLMs wrap JSON in markdown code blocks
            if "```json" in content:
                content = content.split("```json", 1)[1].split("```", 1)[0].strip()
            elif "```" in content:
                content = content.split("```", 1)[1].split("```", 1)[0].strip()
            
            return json.loads(content)
        except Exception:
            return {}

    def _normalize_cascading_output(self, parsed, industry, machinery_type, fault_type):
        parsed = parsed if isinstance(parsed, dict) else {}
        root = parsed.get("root_cause") if isinstance(parsed.get("root_cause"), dict) else {}
        effects = parsed.get("cascading_effects") if isinstance(parsed.get("cascading_effects"), list) else []

        normalized_effects = []
        for idx, effect in enumerate(effects, start=1):
            if not isinstance(effect, dict):
                continue
            possible_faults = effect.get("possible_faults")
            if not isinstance(possible_faults, list):
                possible_faults = []
            clean_faults = [str(item).strip() for item in possible_faults if str(item).strip()][:3]
            if not clean_faults:
                clean_faults = ["Secondary equipment stress", "Protection miscoordination risk"]

            risk = str(effect.get("cascade_risk", "high")).strip().lower()
            if risk not in {"critical", "high", "medium", "low"}:
                risk = "high"

            normalized_effects.append({
                "level": idx,
                "affected_machinery": str(effect.get("affected_machinery", "Downstream Protection System")).strip() or "Downstream Protection System",
                "possible_faults": clean_faults,
                "cascade_risk": risk,
                "cascade_explanation": str(effect.get("cascade_explanation", "Operational stress propagates to downstream assets and increases outage probability.")).strip() or "Operational stress propagates to downstream assets and increases outage probability."
            })

        severity = str(root.get("severity", "high")).strip().lower()
        if severity not in {"critical", "high", "medium", "low"}:
            severity = "high"

        return {
            "root_cause": {
                "industry": str(root.get("industry", industry)).strip() or industry,
                "machinery": str(root.get("machinery", machinery_type)).strip() or machinery_type,
                "fault": str(root.get("fault", fault_type)).strip() or fault_type,
                "severity": severity,
                "explanation": str(root.get("explanation", "Fault condition introduces instability and creates downstream operational risk in connected assets.")).strip() or "Fault condition introduces instability and creates downstream operational risk in connected assets."
            },
            "cascading_effects": normalized_effects,
            "systemic_impact_summary": str(parsed.get("systemic_impact_summary", "The event can propagate through protection, switching, and load-serving assets if not isolated quickly.")).strip() or "The event can propagate through protection, switching, and load-serving assets if not isolated quickly."
        }

    def _local_fallback_analysis(self, fault_json, provider_error):
        fault = fault_json or {}
        fault_type = str(fault.get("fault_type", "Unknown fault"))
        component = str(fault.get("component", "fault_detection_service"))
        severity = str(fault.get("severity", "medium")).lower()

        base_steps = [
            f"Isolate and inspect component: {component}.",
            "Validate sensor and relay telemetry against historical baselines.",
            "Apply protective switching sequence and confirm system stabilization.",
            "Run post-event verification and close incident with operator sign-off."
        ]
        if severity in {"high", "critical"}:
            base_steps.insert(1, "Escalate to on-call admin and dispatch field team immediately.")

        return {
            "root_cause_explanation": (
                f"Groq rate limit or quota blocked analysis. "
                f"Likely root cause for {fault_type} is instability or protection-path anomaly around {component}."
            ),
            "mitigation_plan": base_steps,
            "preventive_recommendations": [
                "Enable proactive threshold alerts for current and voltage drift.",
                "Schedule periodic relay coordination and breaker health checks.",
                "Maintain incident postmortem logs and retrain fault classifier on new events."
            ],
            "confidence_notes": (
                "Fallback analysis generated locally because Groq returned quota/rate-limit error: "
                f"{provider_error[:220]}"
            )
        }
