import json
import os
import time
from urllib import error as urlerror
from urllib import request as urlrequest


class GeminiFaultAnalysisService:
    """Handles structured fault interpretation with Gemini."""

    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "").strip()
        self.model = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
        self.base_url = os.getenv("GEMINI_API_URL", "https://generativelanguage.googleapis.com")
        self.max_retries = int(os.getenv("GEMINI_MAX_RETRIES", "3"))
        fallback_models = os.getenv(
            "GEMINI_FALLBACK_MODELS",
            "gemini-2.0-flash,gemini-1.5-flash-latest,gemini-1.5-pro-latest"
        )
        self.model_candidates = self._build_model_candidates(self.model, fallback_models)

    def analyze_fault(self, fault_json, architecture_context, fault_history):
        if not self.api_key:
            raise RuntimeError("Missing GEMINI_API_KEY. Add it to your environment before using AI fault interpretation.")

        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": self._build_prompt(fault_json, architecture_context, fault_history)
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 900,
                "responseMimeType": "application/json"
            }
        }

        try:
            raw = self._call_with_retry(payload)
            parsed = self._parse_response(raw)
        except RuntimeError as err:
            message = str(err)
            if "HTTP 429" in message or "quota" in message.lower():
                return self._local_fallback_analysis(fault_json, message)
            raise

        return {
            "root_cause_explanation": parsed.get("root_cause_explanation", "No root cause explanation returned."),
            "mitigation_plan": parsed.get("mitigation_plan", []),
            "preventive_recommendations": parsed.get("preventive_recommendations", []),
            "confidence_notes": parsed.get("confidence_notes", "Generated by Gemini based on provided context.")
        }

    def _build_prompt(self, fault_json, architecture_context, fault_history):
        fault_text = json.dumps(fault_json or {}, indent=2)
        architecture_text = json.dumps(architecture_context or {}, indent=2)
        history_text = json.dumps(fault_history or [], indent=2)

        return (
            "You are a senior reliability engineer for an intelligent fault management system.\\n"
            "Analyze the provided fault data, system architecture context, and recent fault history.\\n"
            "Return ONLY valid JSON with this exact schema:\\n"
            "{\\n"
            '  "root_cause_explanation": "string",\\n'
            '  "mitigation_plan": ["step 1", "step 2"],\\n'
            '  "preventive_recommendations": ["recommendation 1", "recommendation 2"],\\n'
            '  "confidence_notes": "string"\\n'
            "}\\n"
            "Be specific, practical, and avoid generic language.\\n"
            "Fault JSON:\\n"
            f"{fault_text}\\n\\n"
            "System Architecture Context:\\n"
            f"{architecture_text}\\n\\n"
            "Recent Fault History:\\n"
            f"{history_text}"
        )

    def _call_with_retry(self, payload):
        body = json.dumps(payload).encode("utf-8")

        last_error = None
        retries = max(1, self.max_retries)

        for model_name in self.model_candidates:
            endpoint = f"{self.base_url}/v1beta/models/{model_name}:generateContent?key={self.api_key}"
            model_not_found = False

            for attempt in range(1, retries + 1):
                request_obj = urlrequest.Request(
                    endpoint,
                    data=body,
                    headers={
                        "Content-Type": "application/json",
                        "Accept": "application/json"
                    },
                    method="POST"
                )

                try:
                    with urlrequest.urlopen(request_obj, timeout=35) as response:
                        return json.loads(response.read().decode("utf-8"))
                except urlerror.HTTPError as err:
                    details = err.read().decode("utf-8", errors="ignore")
                    lower_details = details.lower()
                    last_error = RuntimeError(f"Gemini API HTTP {err.code}: {details[:400]}")

                    if err.code == 404 and ("not found" in lower_details or "listmodels" in lower_details):
                        model_not_found = True
                        break

                    if err.code in {400, 401, 403}:
                        break
                except Exception as err:
                    last_error = RuntimeError(f"Gemini API request failed: {str(err)}")

                if attempt < retries:
                    time.sleep(2 ** (attempt - 1))

            if model_not_found:
                continue

            # Non-404 failure; no need to keep iterating model list.
            break

        raise last_error or RuntimeError(
            "Gemini API request failed after retries and model fallback attempts. "
            "Set GEMINI_MODEL or GEMINI_FALLBACK_MODELS to a supported model from ListModels."
        )

    def _build_model_candidates(self, primary_model, fallback_models_csv):
        seen = set()
        models = []

        for model in [primary_model] + fallback_models_csv.split(","):
            normalized = self._normalize_model_name(model)
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            models.append(normalized)

        return models or ["gemini-2.0-flash"]

    def _normalize_model_name(self, model_name):
        value = str(model_name or "").strip()
        if not value:
            return ""

        # Accept both "models/xxx" and plain model names from environment variables.
        if value.startswith("models/"):
            return value.split("models/", 1)[1]
        return value

    def _parse_response(self, raw_response):
        try:
            candidates = raw_response.get("candidates") or []
            parts = (((candidates[0] or {}).get("content") or {}).get("parts") or []) if candidates else []
            text = (parts[0] or {}).get("text", "") if parts else ""
            text = text.strip()

            if not text:
                return {}

            return json.loads(text)
        except Exception:
            return {}

    def _local_fallback_analysis(self, fault_json, provider_error):
        fault = fault_json or {}
        fault_type = str(fault.get("fault_type", "Unknown fault"))
        component = str(fault.get("component", "fault_detection_service"))
        severity = str(fault.get("severity", "medium")).lower()

        base_steps = [
            f"Isolate and inspect component: {component}.",
            "Validate sensor and relay telemetry against historical baselines.",
            "Apply protective switching sequence and confirm system stabilization.",
            "Run post-event verification and close incident with operator sign-off."
        ]
        if severity in {"high", "critical"}:
            base_steps.insert(1, "Escalate to on-call admin and dispatch field team immediately.")

        return {
            "root_cause_explanation": (
                f"Gemini quota/rate limit blocked cloud analysis. "
                f"Likely root cause for {fault_type} is instability or protection-path anomaly around {component}."
            ),
            "mitigation_plan": base_steps,
            "preventive_recommendations": [
                "Enable proactive threshold alerts for current and voltage drift.",
                "Schedule periodic relay coordination and breaker health checks.",
                "Maintain incident postmortem logs and retrain fault classifier on new events."
            ],
            "confidence_notes": (
                "Fallback analysis generated locally because Gemini returned quota/rate-limit error: "
                f"{provider_error[:220]}"
            )
        }
